version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - myapp-network
  php-fpm:
    image: php:7.4-fpm
    volumes:
      - ./php:/var/www/html
    networks:
      - myapp-network
    command: >
      bash -c "docker-php-ext-install mysqli && php-fpm"
    # O también puedes usar el shell de sh en lugar de bash, dependiendo de la imagen de PHP:
    # command: >
    #   sh -c "docker-php-ext-install mysqli && php-fpm"

  mariadb:
    image: mariadb:latest
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: 1160293
      MYSQL_DATABASE: estudiante
      MYSQL_USER: 1160293
      MYSQL_PASSWORD: 1160293
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - myapp-network

networks:
  myapp-network:
